# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msp/serving/v1/model_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msp/serving/v1/model_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"msp/serving/v1/model_service.proto\x12\x0emsp.serving.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x01\n\x0ePredictRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\x12/\n\x0bingest_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12>\n\x08metadata\x18\x06 \x03(\x0b\x32,.msp.serving.v1.PredictRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb5\x01\n\x0fPredictResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x15\n\rmodel_version\x18\x03 \x01(\t\x12\x14\n\x0cmodel_digest\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\x0c\x12&\n\x06status\x18\x06 \x01(\x0e\x32\x16.msp.serving.v1.Status\x12\x14\n\x0cinference_ms\x18\x07 \x01(\x03\"\x0f\n\rHealthRequest\"/\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t*7\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\x11\n\rINVALID_INPUT\x10\x01\x12\x12\n\x0eINTERNAL_ERROR\x10\x02\x32\xa3\x01\n\x0cModelService\x12J\n\x07Predict\x12\x1e.msp.serving.v1.PredictRequest\x1a\x1f.msp.serving.v1.PredictResponse\x12G\n\x06Health\x12\x1d.msp.serving.v1.HealthRequest\x1a\x1e.msp.serving.v1.HealthResponseBN\n\x15io.msp.gen.serving.v1P\x01Z3github.com/yschiang/msp/msp/gen/servingv1;servingv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msp.serving.v1.model_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025io.msp.gen.serving.v1P\001Z3github.com/yschiang/msp/msp/gen/servingv1;servingv1'
  _globals['_PREDICTREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_STATUS']._serialized_start=594
  _globals['_STATUS']._serialized_end=649
  _globals['_PREDICTREQUEST']._serialized_start=88
  _globals['_PREDICTREQUEST']._serialized_end=342
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_start=295
  _globals['_PREDICTREQUEST_METADATAENTRY']._serialized_end=342
  _globals['_PREDICTRESPONSE']._serialized_start=345
  _globals['_PREDICTRESPONSE']._serialized_end=526
  _globals['_HEALTHREQUEST']._serialized_start=528
  _globals['_HEALTHREQUEST']._serialized_end=543
  _globals['_HEALTHRESPONSE']._serialized_start=545
  _globals['_HEALTHRESPONSE']._serialized_end=592
  _globals['_MODELSERVICE']._serialized_start=652
  _globals['_MODELSERVICE']._serialized_end=815
# @@protoc_insertion_point(module_scope)
