# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: msp/example/v1/defect.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'msp/example/v1/defect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmsp/example/v1/defect.proto\x12\x0emsp.example.v1\"1\n\x0b\x44\x65\x66\x65\x63tInput\x12\x10\n\x08wafer_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\",\n\x0c\x44\x65\x66\x65\x63tOutput\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x42N\n\x15io.msp.gen.example.v1P\x01Z3github.com/yschiang/msp/msp/gen/examplev1;examplev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'msp.example.v1.defect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025io.msp.gen.example.v1P\001Z3github.com/yschiang/msp/msp/gen/examplev1;examplev1'
  _globals['_DEFECTINPUT']._serialized_start=47
  _globals['_DEFECTINPUT']._serialized_end=96
  _globals['_DEFECTOUTPUT']._serialized_start=98
  _globals['_DEFECTOUTPUT']._serialized_end=142
# @@protoc_insertion_point(module_scope)
